version: "3.8"

services:
  fuseki:
    image: stain/jena-fuseki
    container_name: fuseki
    ports:
      - "3030:3030"
    environment:
      - ADMIN_PASSWORD=admin
    command: ["--mem", "/ds"] 

  loader:
    build: ./python_app
    container_name: loader
    depends_on:
      - fuseki